"""Add promotion_year_id to Rotation

Revision ID: 954d43ffd0b2
Revises: cc89905a4537
Create Date: 2025-07-12 17:28:43.066119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '954d43ffd0b2'
down_revision = 'cc89905a4537'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rotations', sa.Column(
        'promotion_year_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'rotations', 'promotion_years', [
                          'promotion_year_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rotations', type_='foreignkey')
    op.drop_column('rotations', 'promotion_year_id')
    # ### end Alembic commands ###
