"""Add speciality table and promotion-speciality relationship

Revision ID: b58b9ddbb314
Revises: 0c3dbbf7057b
Create Date: 2025-07-01 11:43:57.652192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b58b9ddbb314'
down_revision = '0c3dbbf7057b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duree_annees', sa.Integer(), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.add_column('promotions', sa.Column('speciality_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'promotions', 'specialities', ['speciality_id'], ['id'])
    op.drop_constraint('rotations_planning_id_fkey', 'rotations', type_='foreignkey')
    op.create_foreign_key(None, 'rotations', 'plannings', ['planning_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rotations', type_='foreignkey')
    op.create_foreign_key('rotations_planning_id_fkey', 'rotations', 'plannings', ['planning_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'promotions', type_='foreignkey')
    op.drop_column('promotions', 'speciality_id')
    op.drop_table('specialities')
    # ### end Alembic commands ### 