"""Add planning settings table

Revision ID: c73084ccf929
Revises: 5612685bd9df
Create Date: 2025-07-07 06:35:17.709962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c73084ccf929'
down_revision = '5612685bd9df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planning_settings',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('academic_year_start',
                              sa.String(), nullable=False),
                    sa.Column('total_duration_months',
                              sa.Integer(), nullable=False),
                    sa.Column('max_concurrent_students',
                              sa.Integer(), nullable=False),
                    sa.Column('break_days_between_rotations',
                              sa.Integer(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planning_settings')
    # ### end Alembic commands ###
