"""add_is_active_field_to_etudiants

Revision ID: cc89905a4537
Revises: c73084ccf929
Create Date: 2025-07-07 06:53:30.212175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc89905a4537'
down_revision = 'c73084ccf929'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etudiants', sa.Column(
        'is_active', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('etudiants', 'is_active')
    # ### end Alembic commands ###
